version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: academic_search_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  app:
    build: .
    container_name: academic_search_app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - faiss_data:/app/data

volumes:
  redis_data:
  faiss_data: